version: '3.8'

services:
  db:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: todo_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: todo_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/mysql/logs:/var/log/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: